# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1024, 1024))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAcceptDrops(True)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("font: 700 11pt \"Ubuntu Mono\";\n"
"color: #00062b;\n"
"background-color: qradialgradient(cx:0.5, cy:0.4, radius: 0.5,\n"
"                fx:0.5, fy:0.5, stop:0 #00062b,stop:1 #0c004b);\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(860, 600))
        self.frame.setStyleSheet("QFrame {\n"
"    border: 0px;\n"
"    background: transparent;\n"
"}")
        self.debug_label = QtWidgets.QLabel(self.centralwidget)
        self.debug_label.setGeometry(QtCore.QRect(0, 0, 200, 30))
        self.debug_label.setObjectName("debug_label")
        self.debug_label.setText("Debug Label")
        self.debug_label.setStyleSheet("background-color: none; color: white;")

        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.videoLabel = QtWidgets.QLabel(self.frame)
        self.videoLabel.setGeometry(QtCore.QRect(2, 0, 854, 480))
        self.videoLabel.setMinimumSize(QtCore.QSize(854, 480))
        self.videoLabel.setMaximumSize(QtCore.QSize(854, 480))
        self.videoLabel.setBaseSize(QtCore.QSize(200, 200))
        self.videoLabel.setStyleSheet("color: white;\n"
"font-size: 24px;\n"
"background-color: none;\n"
"border: 1px solid #0062d0;\n"
"border-radius: 50% 50%;")
        self.videoLabel.setScaledContents(True)
        self.videoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videoLabel.setObjectName("videoLabel")
        self.signupButton = QtWidgets.QPushButton(self.frame)
        self.signupButton.setGeometry(QtCore.QRect(350, 540, 181, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signupButton.sizePolicy().hasHeightForWidth())
        self.signupButton.setSizePolicy(sizePolicy)
        self.signupButton.setMinimumSize(QtCore.QSize(100, 50))
        self.signupButton.setMaximumSize(QtCore.QSize(200, 100))
        self.signupButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: rgba(0, 0, 0, 30);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font-size: 18px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 45);\n"
"}\n"
"")
        self.signupButton.setObjectName("signupButton")
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.videoLabel.setText(_translate("MainWindow", "Loading..."))
        self.signupButton.setText(_translate("MainWindow", "Sign Up"))
