version: "3.9"
services:
  tcplistener:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: tcpserver
    container_name: "tcp_server"
    expose:
      - "9000"
    volumes:
      - "/data/my_projects/FaceLock/server:/app"
    ports:
      - "9000:9000"
    restart: "always"
    depends_on:
      - db
  db:
    image: postgres:16.1
    container_name: "fl_postgres"
    hostname: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
    restart: unless-stopped
    volumes:
      - ${POSTGRES_DATA_DIR:-./postgres-data}:/var/lib/postgresql/data
